POST http://localhost:3333/user/create
Content-Type: application/json

{
  "username": "mrUser",
  "password": "bajskorv"
}

###
POST http://localhost:3333/user/login
Content-Type: application/json

{
  "username": "mrUser",
  "password": "bajskorv"
}